/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A loaded MLX language model, ready to chat.
 *
 * There is no session/conversation handle to manage: like the OpenAI and
 * Anthropic chat completion APIs, every call passes the full message
 * list, and an internal, always-on prompt-cache pool transparently
 * reuses KV state for whatever prefix (if any) a previous call already
 * computed - including from a *different* logical conversation that
 * happens to share a prefix (e.g. a common system prompt).
 *
 * ```js
 * import { MlexModel } from 'mlex';
 *
 * const model = await MlexModel.load('./models/Qwen3-0.6B-4bit');
 * const messages = [{ role: 'user', content: 'Say hi in five words.' }];
 * const { text } = await model.generate(messages, { maxTokens: 64 });
 * console.log(text);
 *
 * // Continue the conversation by growing `messages` yourself and
 * // calling `generate` again - the shared prefix is served from cache.
 * messages.push({ role: 'assistant', content: text });
 * messages.push({ role: 'user', content: "What's 2+2?" });
 * const { text: reply2 } = await model.generate(messages, { maxTokens: 64 });
 * ```
 */
export declare class MlexModel {
  /**
   * Load a model directory containing `config.json`, safetensors
   * shards, `tokenizer.json`, and (optionally) `chat_template.jinja`.
   *
   * Supports dense bf16/fp16 checkpoints as well as every quantization
   * scheme MLX ships (affine 2-8 bit at any group size, mxfp4, mxfp8,
   * nvfp4) and mixed per-layer precision checkpoints such as OptiQ or
   * Google QAT exports, wherever the underlying architecture is wired up.
   */
  static load(modelPath: string): Promise<MlexModel>
  /**
   * Generate a reply to `messages` (the full transcript so far - see
   * the type-level docs for how caching works across calls).
   *
   * Passing `options.tools` renders an OpenAI-style function schema
   * into the chat template and parses any tool calls back out of the
   * reply into the result's `toolCalls` (empty when no tools were
   * passed, or none were called). When `onToken` is provided it is
   * invoked once per generated token (streaming); the returned Promise
   * always resolves once generation finishes.
   *
   * Passing `options.enableThinking` opts into "thinking" mode on
   * models whose chat template supports it; any resulting reasoning
   * span is stripped out of `text` and returned separately as
   * `reasoning` (`options.reasoningBudgetTokens` caps how long that
   * span may run before it's force-closed).
   */
  generate(messages: Array<JsChatMessage>, options?: JsGenerateOptions | undefined | null, onToken?: (((err: Error | null, arg: JsToken) => void)) | undefined | null): Promise<JsGenerateResult>
  /** Whether this checkpoint accepts image (and video-as-frames) input. */
  supportsImages(): boolean
  /** Whether this checkpoint accepts audio input. */
  supportsAudio(): boolean
}

/**
 * One chat turn, mirroring the OpenAI-style `{role, content}` shape used
 * by every JS chat API, plus optional media attachments (raw encoded
 * file bytes) for multimodal models: `images` (JPEG/PNG/...), `audios`
 * (WAV/MP3/...), `videos` (MP4/WebM/..., uniformly sampled into frames
 * through the vision tower).
 *
 * There is no separate conversation/session handle - like the OpenAI and
 * Anthropic chat APIs, callers pass the *full* running transcript on
 * every call (growing this array themselves between calls) and
 * `MlexModel.generate`'s internal prompt-cache pool transparently reuses
 * KV state for whatever prefix was already computed by a previous call.
 */
export interface JsChatMessage {
  role: string
  content: string
  images?: Array<Buffer>
  audios?: Array<Buffer>
  videos?: Array<Buffer>
  /**
   * Set on a `role: "tool"` turn: which previously-issued call this
   * result answers.
   */
  toolCallId?: string
  /**
   * Set on an assistant turn that issued tool calls (as returned by a
   * prior `generate` call's `toolCalls`, when `options.tools` was
   * passed).
   */
  toolCalls?: Array<JsToolCall>
  /**
   * Set on an assistant turn to round-trip its reasoning/"thinking"
   * content (as returned by a prior `generate` call's `reasoning`)
   * back into history, matching templates that special-case it
   * (Gemma4/Qwen-style).
   */
  reasoningContent?: string
}

/**
 * Sampling + length controls for a single `generate` call, plus an
 * optional tool ("function") declaration list.
 *
 * Passing `tools` renders an OpenAI-style function schema into the chat
 * template and parses any tool calls back out of the reply (populating
 * [`JsGenerateResult::tool_calls`]) - there is no separate
 * `generateWithTools` method, this is the only entry point.
 */
export interface JsGenerateOptions {
  maxTokens?: number
  temperature?: number
  topP?: number
  topK?: number
  seed?: number
  tools?: Array<JsTool>
  /**
   * Opt into "thinking" mode on models whose chat template supports it
   * (Qwen3/3.5/3.6, Gemma4, MiniCPM5, NemotronH, ...). Leaving this
   * unset keeps the template's own default, which for all of those is
   * reasoning off.
   */
  enableThinking?: boolean
  /**
   * Cap, in tokens, on how long the model may spend inside a detected
   * reasoning span before it's force-closed and generation moves on to
   * the final answer - mirroring Anthropic's extended-thinking
   * `budget_tokens`. Unset means no cap.
   */
  reasoningBudgetTokens?: number
}

/** The resolved value of [`MlexModel::generate`]. */
export interface JsGenerateResult {
  text: string
  /**
   * Tool calls parsed out of `text`; empty unless `options.tools` was
   * passed and the model actually issued one or more calls.
   */
  toolCalls: Array<JsToolCall>
  /**
   * Token accounting for this call, mirroring the `usage` block
   * OpenAI/Anthropic return alongside a chat completion.
   */
  usage: JsUsage
  /**
   * Extracted reasoning/"thinking" content, if the model emitted a
   * recognized reasoning span - present regardless of whether
   * `options.enableThinking` was explicitly set, since some
   * checkpoints reason unconditionally. `text` never includes this
   * span; pass it back via `reasoningContent` on the next assistant
   * turn to preserve it in multi-turn history.
   */
  reasoning?: string
}

/**
 * One streamed token, passed to the optional `onToken` callback of
 * [`MlexModel::generate`].
 */
export interface JsToken {
  id: number
  text: string
  finished: boolean
  /**
   * Which span this token belongs to - `"text"` (the final answer),
   * `"reasoning"` (inside a "thinking" span), or `"toolCall"` (raw,
   * not-yet-parsed tool-call syntax) - mirroring OpenAI/Anthropic's
   * typed streaming deltas so a UI can render each separately live,
   * rather than only being able to split them apart from the final
   * `{ text, reasoning, toolCalls }` once generation finishes.
   * Best-effort at token granularity - see `mlex::streaming`.
   */
  kind: string
}

/**
 * An OpenAI-style tool ("function") declaration, passed via
 * `options.tools` to `MlexModel.generate`.
 */
export interface JsTool {
  name: string
  description?: string
  /**
   * JSON Schema for the function's arguments (e.g.
   * `{ type: "object", properties: {...} }`).
   */
  parameters: JsonValue
}

/** A parsed tool call recovered from model output. */
export interface JsToolCall {
  id: string
  name: string
  /** JSON-encoded arguments object. */
  argumentsJson: string
}

/** Token accounting for one [`MlexModel::generate`] call. */
export interface JsUsage {
  /**
   * Total input tokens for this call's fully-rendered prompt (the sum
   * of `cachedTokens` and however many had to be freshly computed).
   */
  promptTokens: number
  /**
   * How many of `promptTokens` were served from the internal
   * prompt-cache pool (an exact-prefix hit) rather than run through
   * the model this call.
   */
  cachedTokens: number
  /** Tokens generated in this call's reply. */
  completionTokens: number
}
